### ISSUE TITLE
Cannot update a component (`DataKeyPair`) while rendering a different component (`DataKeyPair`).

### ISSUE THREAD

**Issue by mashirozx** [Himself65/rich-data#24]
Warning: Cannot update a component (`DataKeyPair`) while rendering a different component (`DataKeyPair`). To locate the bad setState() call inside `DataKeyPair`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render

Didn't track more detail, maybe there is some setState in Promise, and the component has already been destroyed when the promise was resolved.

**Comment by himself65** [comment]
Could you please give the example code?

**Comment by himself65** [comment]
I see the bug
