### ISSUE TITLE
Want the VSCode theme and font in the picture.

### ISSUE THREAD

**Issue by PaulChess** [Himself65/rich-data#34]
A special attention:  

I think the combination of the VSCode theme and font in this picture looks great. May I ask if you can provide me with the specific names of the theme and font?  Thank you very much.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/69644161/226602545-5814e8a9-12ff-4744-8753-226b064c9d7a.png">

**Comment by himself65** [comment]
https://marketplace.visualstudio.com/items?itemName=KYDronePilot.material-deep-ocean-theme

**Comment by himself65** [comment]
https://material-theme.com/docs/reference/color-palette/
